#page title
# Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.
page_title: Life in the UK Untangled

# App Info
# Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_id: 1512489096

# Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
appstore_link:

# Enter Google Play Store URL.
playstore_link:

# Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
# Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
presskit_download_link:

# Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_icon: assets/logo.png

# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_name: Life in the UK Untangled

# Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: £4.99
app_description: Pass the test without the book

# Set to true to show a smart app banner at top of page on mobile devices.
enable_smart_app_banner: true



# Information About Yourself
your_name: Dripl
your_link: https://dripl.co.uk
your_city:
email_address: hello@dripl.co.uk
facebook_username:
instagram_username:
twitter_username: alixedi
github_username: alixedi
youtube_username:


# Feature List
features:

  - title: From migrants
    description: We passed our Life in the UK tests in 2019. We know what it takes & we put everything we know in this app.
    fontawesome_icon_name: heart

  - title: Do not buy the book
    description: Seriously. Don't. All the content you need is baked into the app. What't more, the content is structured to help you memorize it.
    fontawesome_icon_name: check-square

  - title: Privacy first
    description: We do not want to know who you are. We do not want to help people sell you stuff. We just want you to pass the test.
    fontawesome_icon_name: lock

  - title: Sprinkle of science
    description: We have designed the app with spaced repetitions. Questions will repeat until you get them right several times.
    fontawesome_icon_name: brain

  - title: A thousand questions
    description: The app has a thousand carefully crafted questions, their answers & detailed write-ups that explain the answers.
    fontawesome_icon_name: list

  - title: Beautiful, slick UI
    description: Most test prep apps in the AppStore give us eye sores. We have worked hard to make this one a joy to use.
    fontawesome_icon_name: palette


# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.jpg
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

# Set to: blue, black, yellow, coral or white.
device_color: black

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
